@startuml Architecture
skinparam sequenceArrowThickness 2
frame databases {
    database "CommunityDB" #green
    database "PostDB0" #GreenYellow
    database "PostDB1" #GreenYellow
    database "PostDBN" #GreenYellow
}
CommunityDB -[dashed]- PostDB0
CommunityDB -[dashed]- PostDB1
CommunityDB -[dashed]- PostDBN
PostDBN ~ PostDB1 

component WebServer as "Web server" #YellowGreen
component LemmyFetcher as "Lemmy fetcher" #YellowGreen
component CommunityWorker as "Community worker" #green
component DatabaseService as "Database service" #green

DatabaseService --> databases

WebServer --> DatabaseService
CommunityWorker --> CommunityDB : Exponential backoff
LemmyFetcher --> PostDB0
LemmyFetcher --> PostDB1
LemmyFetcher --> PostDBN

queue Messageq #YellowGreen
CommunityWorker --> Messageq
Messageq --> LemmyFetcher : Queue-trigger

boundary Lemmy
LemmyFetcher --> Lemmy
@enduml