version: "3.8"
services:
  CWebServer:
    image: cwebserver
    ports:
      - 8000:8000
    volumes:
      - ./CWebServer:/app
    environment:
      - CWEB_SECRET_KEY=123
      - CDATABASESERVICE_SERVICE_HOST=cdatabaseservice
      - PYTHONUNBUFFERED=1
  CWorker:
    image: cworker
    volumes:
      - ./CWorker:/app
    environment:
      - CWORKER_DATABASE_HOST=communitydb
      - CWORKER_DATABASE_NAME=CommunityDB
      - CWORKER_REFRESH_RATE=60
      - CWORKER_MESSAGE_QUEUE_HOST=host.docker.internal
      - CWORKER_MESSAGE_QUEUE_USERNAME=default_user_6-iQEnfJt6RZdHLvbDU
      - CWORKER_MESSAGE_QUEUE_PASSWORD=r-Tyr9yKfd8v0ZZMD62C2JlfOhn0_HY2
      - CWORKER_MESSAGE_QUEUE_QUEUE=update-community
      - CWORKER_BATCH_SIZE=2
      - CWORKER_LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
  CFetcher:
    image: cfetcher
    volumes:
      - ./CFetcher:/app
    environment:
      - CFETCHER_POSTS_DATABASE_HOST=postdb
      - CFETCHER_POSTS_DATABASE_NAME=PostDB
      - CFETCHER_COMMUNITY_DATABASE_HOST=communitydb
      - CFETCHER_COMMUNITY_DATABASE_NAME=CommunityDB
      - CFETCHER_MESSAGE_QUEUE_HOST=host.docker.internal
      - CFETCHER_MESSAGE_QUEUE_USERNAME=default_user_6-iQEnfJt6RZdHLvbDU
      - CFETCHER_MESSAGE_QUEUE_PASSWORD=r-Tyr9yKfd8v0ZZMD62C2JlfOhn0_HY2
      - CFETCHER_MESSAGE_QUEUE_QUEUE=update-community
      - CFETCHER_LOG_LEVEL=DEBUG
  communitydb:
    image: mongo
    command: --quiet --syslog
    expose:
      - "27017"
    volumes:
      - community-db-data:/data/db
      - mongo-config-community-db:/data/configdb
  postdb:
    image: mongo
    command: --quiet --syslog
    expose:
      - "27017"
    volumes:
      - post-db-data:/data/db
      - mongo-config-post-db:/data/confidb
  cdatabaseservice:
    image: cdatabaseservice:latest
    environment:
      - CDatabaseService__CommunityDB__ConnectionString=communitydb
      - CDatabaseService__CommunityDB__DatabaseName=CommunityDB
      - CDatabaseService__CommunityDB__CollectionName=communities
      - CDatabaseService__PostDB__ConnectionString=postdb
      - CDatabaseService__PostDB__DatabaseName=PostDB
      - CDatabaseService__PostDB__CollectionName=posts
volumes:
  community-db-data:
  post-db-data:
  mongo-config-community-db:
  mongo-config-post-db:
